Add contacts area section
PNdunguMaina/Setup-and-mobile-version-skeleton pull request #3
Opened 2022-06-01 13:24 UTC by PNdunguMaina

In this project I did the following:

- Updated index.html file for the contacts section
- Updated style.css file for the contacts section
- Collaborated with two of my Microverse colleagues on this part of the project

2022-06-01 14:38 UTC, danmainah requested changes
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-01 14:38 UTC, danmainah commented on index.html
> +      <form class="contacts-form" action="#" method="post">
- [ ] Kindly complete your action method, and ensure to integrate with [formspree service](https://formspree.io/html).

2022-06-01 14:38 UTC, danmainah commented on index.html
> +      <a class="button button-frame" href="#">see Project</a>
- [ ] Kindly ensure your button, is a `<button> element or an `<input>` element , if you choose `<input>` element ensure  you add type `submit`.Also, ensure the hover effect is aligned to the design given.

2022-06-01 14:38 UTC, danmainah commented on index.html
> +            />
- [ ] Kindly add the validation for the name input field, and add the `maxlength="30"` attribute, which checks the length of the input and ensures it's not beyond 30 characters.

2022-06-01 14:38 UTC, danmainah commented on index.html
> +            ></textarea>
- [ ]  Kindly add the validation for the message input field, and add the `maxlength="500"` attribute, which checks the length of the input and ensures it's not beyond 500 characters.

2022-06-01 14:38 UTC, danmainah commented on index.html
> +      <form class="contacts-form" action="#" method="post">
- [ ] Kindy ensure all input fields have the `required` attribute to activate the validation on submit.

2022-06-01 21:23 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey  @PNdunguMaina 😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

[Optional] All fields must be `required`. Please add `required` attribute in all input fields 👍🏻 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 21:28 UTC, merged

2022-06-09 08:51 UTC, Meltrust reviewed
Hi @PNdunguMaina,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Last week's reviewers' suggestions were implemented✔️ 
- The app works well✔️ 
- The form works✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._